# Translations template for glance.
# Copyright (C) 2015 ORGANIZATION
# This file is distributed under the same license as the glance project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2015.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: glance 2015.1.dev17\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2015-02-20 06:02+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: glance/scrubber.py:459
#, python-format
msgid "Starting Daemon: wakeup_time=%(wakeup_time)s threads=%(threads)s"
msgstr ""

#: glance/scrubber.py:473
msgid "Daemon Shutdown on KeyboardInterrupt"
msgstr ""

#: glance/scrubber.py:485
#, python-format
msgid "Initializing scrubber with configuration: %s"
msgstr ""

#: glance/scrubber.py:558
#, python-format
msgid "Scrubbing image %(id)s from %(count)d locations."
msgstr ""

#: glance/scrubber.py:581
#, python-format
msgid "Image %s has been deleted."
msgstr ""

#: glance/scrubber.py:633
#, python-format
msgid "Getting images deleted before %s"
msgstr ""

#: glance/api/middleware/cache.py:61
msgid "Initialized image cache middleware"
msgstr ""

#: glance/api/middleware/cache_manage.py:74
msgid "Initialized image cache management middleware"
msgstr ""

#: glance/api/middleware/gzip.py:35
msgid "Initialized gzip middleware"
msgstr ""

#: glance/api/v1/images.py:686
#, python-format
msgid "Uploaded data of image %s from request payload successfully."
msgstr ""

#: glance/api/v1/images.py:737
msgid "Triggering asynchronous copy from external source"
msgstr ""

#: glance/api/v1/upload_utils.py:126
#, python-format
msgid "Cleaning up %s after exceeding the quota"
msgstr ""

#: glance/api/v1/upload_utils.py:175
#, python-format
msgid ""
"Image %s could not be found after upload. The image may have been deleted"
" during the upload."
msgstr ""

#: glance/async/eventlet_executor.py:50
#, python-format
msgid ""
"Eventlet executor picked up the execution of task ID %(task_id)s of task "
"type %(task_type)s"
msgstr ""

#: glance/async/taskflow_executor.py:87
#, python-format
msgid ""
"Taskflow executor picked up the execution of task ID %(task_id)s of task "
"type %(task_type)s"
msgstr ""

#: glance/cmd/replicator.py:371
#, python-format
msgid "Storing: %s"
msgstr ""

#: glance/cmd/replicator.py:444
#, python-format
msgid "Considering: %s"
msgstr ""

#: glance/cmd/replicator.py:470 glance/cmd/replicator.py:545
#, python-format
msgid "Image %s metadata has changed"
msgstr ""

#: glance/cmd/replicator.py:552
#, python-format
msgid "Image %s is being synced"
msgstr ""

#: glance/common/wsgi.py:270
#, python-format
msgid "Starting %d workers"
msgstr ""

#: glance/common/wsgi.py:285
#, python-format
msgid "Removing dead child %s"
msgstr ""

#: glance/common/wsgi.py:291
msgid "All workers have terminated. Exiting"
msgstr ""

#: glance/common/wsgi.py:300
msgid "Caught keyboard interrupt. Exiting."
msgstr ""

#: glance/common/wsgi.py:326
#, python-format
msgid "Child %d exiting normally"
msgstr ""

#: glance/common/wsgi.py:331
#, python-format
msgid "Started child %s"
msgstr ""

#: glance/common/wsgi.py:355
msgid "Starting single process server"
msgstr ""

#: glance/common/scripts/__init__.py:32
#, python-format
msgid "Loading known task scripts for task_id %(task_id)s of type %(task_type)s"
msgstr ""

#: glance/common/scripts/image_import/main.py:41
#, python-format
msgid "Task %(task_id)s beginning import execution."
msgstr ""

#: glance/common/scripts/image_import/main.py:152
#, python-format
msgid "Task %(task_id)s: Got image data uri %(data_uri)s to be imported"
msgstr ""

#: glance/common/scripts/image_import/main.py:161
#, python-format
msgid "Task %(task_id)s: Could not import image file %(image_data)s"
msgstr ""

#: glance/db/simple/api.py:56
#, python-format
msgid "Calling %(funcname)s: args=%(args)s, kwargs=%(kwargs)s"
msgstr ""

#: glance/db/simple/api.py:62
#, python-format
msgid "Returning %(funcname)s: %(output)s"
msgstr ""

#: glance/db/sqlalchemy/metadata.py:170
#, python-format
msgid "Skipping  namespace %s. It already exists in the database."
msgstr ""

#: glance/db/sqlalchemy/metadata.py:242
#, python-format
msgid "File %s loaded to database."
msgstr ""

#: glance/db/sqlalchemy/metadata.py:244
msgid "Metadata loading finished"
msgstr ""

#: glance/db/sqlalchemy/metadata.py:256
#, python-format
msgid "Table %s has been cleared"
msgstr ""

#: glance/db/sqlalchemy/metadata.py:347
#, python-format
msgid "Namespace %(namespace)s saved in %(file)s"
msgstr ""

#: glance/db/sqlalchemy/migrate_repo/schema.py:98
#, python-format
msgid "creating table %(table)s"
msgstr ""

#: glance/db/sqlalchemy/migrate_repo/schema.py:104
#, python-format
msgid "dropping table %(table)s"
msgstr ""

#: glance/db/sqlalchemy/migrate_repo/versions/017_quote_encrypted_swift_credentials.py:72
msgid ""
"'metadata_encryption_key' was not specified in the config file or a "
"config file was not specified. This means that this migration is a NOOP."
msgstr ""

#: glance/image_cache/__init__.py:71
#, python-format
msgid "Image cache loaded driver '%s'."
msgstr ""

#: glance/image_cache/__init__.py:81 glance/image_cache/__init__.py:100
msgid "Defaulting to SQLite driver."
msgstr ""

#: glance/image_cache/prefetcher.py:84
#, python-format
msgid "Successfully cached all %d images"
msgstr ""

#: glance/image_cache/drivers/sqlite.py:414
#: glance/image_cache/drivers/xattr.py:342
#, python-format
msgid "Not queueing image '%s'. Already cached."
msgstr ""

#: glance/image_cache/drivers/sqlite.py:419
#: glance/image_cache/drivers/xattr.py:347
#, python-format
msgid "Not queueing image '%s'. Already being written to cache"
msgstr ""

#: glance/image_cache/drivers/sqlite.py:425
#: glance/image_cache/drivers/xattr.py:353
#, python-format
msgid "Not queueing image '%s'. Already queued."
msgstr ""

#: glance/image_cache/drivers/sqlite.py:443
#, python-format
msgid "Removed invalid cache file %s"
msgstr ""

#: glance/image_cache/drivers/sqlite.py:457
#, python-format
msgid "Removed stalled cache file %s"
msgstr ""

#: glance/image_cache/drivers/xattr.py:399
#, python-format
msgid "Reaped %(reaped)s %(entry_type)s cache entries"
msgstr ""

#: glance/quota/__init__.py:330
#, python-format
msgid "Cleaning up %s after exceeding the quota."
msgstr ""

#: glance/registry/api/v1/images.py:343 glance/registry/api/v1/images.py:386
#: glance/registry/api/v1/images.py:491
#, python-format
msgid "Image %(id)s not found"
msgstr ""

#: glance/registry/api/v1/images.py:349 glance/registry/api/v1/images.py:381
#: glance/registry/api/v1/images.py:503
#, python-format
msgid "Access denied to image %(id)s but returning 'not found'"
msgstr ""

#: glance/registry/api/v1/images.py:371
#, python-format
msgid "Successfully deleted image %(id)s"
msgstr ""

#: glance/registry/api/v1/images.py:375
#, python-format
msgid "Delete denied for public image %(id)s"
msgstr ""

#: glance/registry/api/v1/images.py:415
#, python-format
msgid "Rejecting image creation request for invalid image id '%(bad_id)s'"
msgstr ""

#: glance/registry/api/v1/images.py:428
#, python-format
msgid "Successfully created image %(id)s"
msgstr ""

#: glance/registry/api/v1/images.py:482
#, python-format
msgid "Updating metadata for image %(id)s"
msgstr ""

#: glance/registry/api/v1/images.py:497
#, python-format
msgid "Update denied for public image %(id)s"
msgstr ""

#: glance/registry/api/v1/members.py:198
#, python-format
msgid "Successfully updated memberships for image %(id)s"
msgstr ""

#: glance/registry/api/v1/members.py:271
#, python-format
msgid "Successfully updated a membership for image %(id)s"
msgstr ""

#: glance/registry/api/v1/members.py:320
#, python-format
msgid "Successfully deleted a membership from image %(id)s"
msgstr ""

